Set up linters
od-c0d3r/gitH pull request #1
Opened 2020-10-19 14:50 UTC by od-c0d3r

1st pull req

2020-10-19 15:04 UTC, elisha2kyakpo1 requested changes

2020-10-19 15:04 UTC, elisha2kyakpo1 commented on index.html
> +      This is my world
Please follow the instruction on the header message, should read "Hello world"

2020-10-19 15:04 UTC, elisha2kyakpo1 commented on index.html
> +      This is my world
Everything looks good except for the header message.

2020-10-19 15:42 UTC, od-c0d3r commented on index.html
> +      This is my world
Thank you, code updated

2020-10-19 15:51 UTC, elisha2kyakpo1 commented
It's good to see you putting in a lot of effort

2020-10-20 04:49 UTC, od-c0d3r commented
Thanks to @iam-Akshat for hinting me the Proplem with yml file.

2020-10-20 20:44 UTC, merged

2020-10-20 20:45 UTC, od-c0d3r reviewed
all good